# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure BIND paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ bind_uid }}"
    group: "{{ bind_gid }}"
  with_items:
    - "{{ bind_base_path }}"
    - "{{ bind_config_path }}"
    - "{{ bind_cache_path }}"
    - "{{ bind_data_path }}"
    - "{{ bind_bin_path }}"

- name: Ensure BIND support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ bind_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ bind_uid }}"
    group: "{{ bind_gid }}"
  with_items:
    - env

- name: Ensure BIND configuration files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config/{{ item }}.j2"
    dest: "{{ bind_config_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ bind_uid }}"
    group: "{{ bind_gid }}"
  with_items:
    - named.conf
    - named-acl.conf
    - named-controls.conf
    - named-key.conf
    - named-logging.conf
    - named-options.conf
    - named-zone.conf

- name: Ensure BIND bin scripts installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/bin/{{ item }}.j2"
    dest: "{{ bind_bin_path }}/{{ item }}"
    mode: "0755"
    owner: "{{ bind_uid }}"
    group: "{{ bind_gid }}"
  with_items:
    - rndc

- name: Ensure BIND container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ bind_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ bind_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else bind_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure BIND container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ bind_container_image }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed
  changed_when: "'Downloaded newer image' in result.stdout"

- name: Ensure BIND container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ bind_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: bind_network_creation_result

- name: Ensure BIND container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ bind_container_network }}
  register: bind_network_creation_result
  changed_when: bind_network_creation_result.rc == 0
  failed_when: bind_network_creation_result.rc != 0 and 'already exists' not in bind_network_creation_result.stderr

- name: Ensure BIND systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/bind.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ bind_identifier }}.service"
    mode: "0644"
